### ISSUE TITLE
 Server name is already used, uniqueness error

### ISSUE THREAD

**Issue by mxmxchere** [23technologies/machine-controller-manager-provider-hcloud#4]
**What happened**:
a machine is created that already exists

**What you expected to happen**:
an existing machine should be detected and not be created multiple times.

**How to reproduce it (as minimally and precisely as possible)**:
unfortunately this error is not reproducable releaibly, but it happnens quite often. try to scale up and down a cluster

**Anything else we need to know**:
error log:
```
task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--23ke-ci--23ke-run-cef1/23ke-run-cef1 to become ready: error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'machine(s) failed: 1 error occurred: "shoot--23ke-ci--23ke-run-cef1-worker-cx41-fsn1-dc14-c6cb8-bf7dj": Cloud provider message - machine codes error: code = [Unavailable] message = [server name is already used (uniqueness_error)]'
```

**Comment by NotTheEvilOne** [comment]
Most cases this error happens either while the machine gets provisioned and the deployment is changed or rescaled and interrupted therefore or after Hetzner failed to complete API calls expected like the VM being "invisible" for the API while cleanup.

An reuse of the existing instance is not possible because of its unclear state. A fix needs to delete the old instance after verification that it is an failed creation attempt.

Workaround for the issue is to either manually delete the VM in question using Hetzner Cloud utilities or wait for Gardener cleanup to happen.

**Comment by mxmxchere** [comment]
I just had the case that the machines existed but were powered off, poweron helped and the nodes registered successfully to the cluster, but the extension kept the "failed state" and the shoot could not progress overall. maybe if the uniqueness error occurs a check whether the machine is off and a successive poweron could help.
